// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtyarVVuMgbM7CK8QZ1WEEkZl_pnd4mAc',
    appId: '1:9587985826:web:33b01acc61a9dd4ff076fb',
    messagingSenderId: '9587985826',
    projectId: 'sustainable-food-8bedf',
    authDomain: 'sustainable-food-8bedf.firebaseapp.com',
    storageBucket: 'sustainable-food-8bedf.firebasestorage.app',
    measurementId: 'G-BN6FXMV17X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDXEU5-Yp49jv_m7zwnSkltfKYtxxogFg',
    appId: '1:9587985826:android:762ee59362b0ffa3f076fb',
    messagingSenderId: '9587985826',
    projectId: 'sustainable-food-8bedf',
    storageBucket: 'sustainable-food-8bedf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJyx2cuaiXZ0x5kPXNFpPBgk0h9FP5yd8',
    appId: '1:9587985826:ios:c5eaef751d53c1e2f076fb',
    messagingSenderId: '9587985826',
    projectId: 'sustainable-food-8bedf',
    storageBucket: 'sustainable-food-8bedf.firebasestorage.app',
    iosBundleId: 'com.example.climateSmartFarming2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJyx2cuaiXZ0x5kPXNFpPBgk0h9FP5yd8',
    appId: '1:9587985826:ios:c5eaef751d53c1e2f076fb',
    messagingSenderId: '9587985826',
    projectId: 'sustainable-food-8bedf',
    storageBucket: 'sustainable-food-8bedf.firebasestorage.app',
    iosBundleId: 'com.example.climateSmartFarming2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtyarVVuMgbM7CK8QZ1WEEkZl_pnd4mAc',
    appId: '1:9587985826:web:f6b771e931cdadc3f076fb',
    messagingSenderId: '9587985826',
    projectId: 'sustainable-food-8bedf',
    authDomain: 'sustainable-food-8bedf.firebaseapp.com',
    storageBucket: 'sustainable-food-8bedf.firebasestorage.app',
    measurementId: 'G-DR1LBB5QY9',
  );
}
